### ISSUE TITLE
[BUG] Trying to select more than 1 object shows error message box

### ISSUE THREAD

**Issue by Qwertyus3D** [Duude92/hammertime#25] opened 2024-05-18 15:16 UTC
Using Ctrl to select more than any 1 object causes error message. Both in 3D & 2D.

> Input string was not in a correct format. (System.FormatException)
>    at System.Text.ValueStringBuilder.ThrowFormatError()
>    at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
>    at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
>    at Sledge.BspEditor.Modification.ChangeHandling.SelectionHandler.UpdateText(Selection selection)
>    at Sledge.BspEditor.Modification.ChangeHandling.SelectionHandler.Changed(Change change)
>    at Sledge.BspEditor.Modification.ChangeHandling.ChangeHandler.Changed(Change change)
>    at LogicAndTrick.Oy.InMemoryMessageBus.<>c__DisplayClass5_0`1.<<Subscribe>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at LogicAndTrick.Oy.InMemoryMessageBus.Publish[T](String name, T obj, Volume volume, CancellationToken token)

**Comment by Duude92** [comment] 2024-05-18 18:23
Fixed with 1557fd9 in #1.
Additionally fixed multiple entity selection saving.

**Comment by Qwertyus3D** [comment] 2024-05-18 23:54
That build is broken, made you to get stuck in any opened window of object's properties.

**Comment by Duude92** [comment] 2024-05-19 05:52
Fixed with 637a7c5

**Comment by Qwertyus3D** [comment] 2024-05-19 16:27
Still see the same error message.

**Comment by Duude92** [comment] 2024-05-19 16:47
I dont understand, please provide more information and way to reproduce.
[See the video](https://youtu.be/IyaFZBWBGsM)

**Comment by Qwertyus3D** [comment] 2024-05-19 19:46
I have latest app version, and have installed several recent builds previously. Any build shows me error message as mentioned above. I do nothing specific, just: select 1 object (any), hold Ctrl, select literally any other object (of the same type or not - doesn't matter) -> Error. The objects still remain selected as a group. I can close error message, add any other object to the selection, but every time I get error message again.
![selerr](https://github.com/Duude92/hammertime/assets/98685264/cecfb295-ee39-4ae3-b4c2-766085001c46)

**Comment by Duude92** [comment] 2024-05-20 06:24
Can you please update application, I have changed ExceptionWindow to provide a bit more information.
Instead of additional info, I've added build branch and build time, check if branch is "latest" and not "latest-origin-editing-feature" which is closed, or you could notify me in Discord: link4999

**Comment by Duude92** [comment] 2024-05-20 14:47
Bug seems to be fixed. Related to translation.

**Closed by Duude92** 2024-05-20 14:47 UTC
Labels: bug
